# Generated by Django 4.2.2 on 2023-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_item', models.CharField(max_length=512, verbose_name='Обновление')),
                ('notifications_link', models.CharField(max_length=512, verbose_name='Ссылка')),
                ('read', models.BooleanField(default='False', verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
