# Generated by Django 4.2.2 on 2023-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_notification_notifications_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notifications_model',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notifications_model_pk',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifications_name',
            field=models.CharField(default='a', max_length=512, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notifications_type',
            field=models.CharField(default='a', max_length=512, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
