# Generated by Django 4.2.2 on 2023-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_notification_notifications_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notifications_link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notifications_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notifications_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifications_message',
            field=models.CharField(default='a', max_length=512, verbose_name='Уведомление'),
            preserve_default=False,
        ),
    ]
