# Generated by Django 4.2.2 on 2023-11-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("admingo", "0004_remove_notification_notifications_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Время",
            ),
            preserve_default=False,
        ),
    ]
