# Generated by Django 4.2.2 on 2023-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, verbose_name='Время подписки')),
                ('unsubscription_date', models.DateTimeField(blank=True, verbose_name='Время подписки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылка',
            },
        ),
    ]
