# Generated by Django 4.2.2 on 2023-08-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='unsubscription_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отписки'),
        ),
    ]
