# Generated by Django 4.2.2 on 2023-08-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_emailsubscription_unsubscription_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
