# Generated by Django 4.2.2 on 2023-08-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank='True', null='True', verbose_name='Ответ'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
