# Generated by Django 4.2.2 on 2023-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_feedback_reply_alter_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reply_status',
            field=models.BooleanField(default=False, verbose_name='Статус ответа'),
        ),
    ]
