# Generated by Django 4.2.2 on 2023-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_feedback_reply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_site', models.TextField(verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'О сайте',
                'verbose_name_plural': 'О сайте',
            },
        ),
    ]
