# Generated by Django 4.2.2 on 2023-08-28 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_aboutsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsite',
            name='about_site',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
