# Generated by Django 4.2.2 on 2023-09-01 10:31

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_aboutsite_about_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('about_site_image', imagekit.models.fields.ProcessedImageField(blank=True, default='static/blog/img/admin_avatar.png', upload_to='avatars/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'О сайте',
                'verbose_name_plural': 'О сайте',
            },
        ),
        migrations.DeleteModel(
            name='AboutSite',
        ),
        migrations.AddField(
            model_name='emailsubscription',
            name='email_hash',
            field=models.CharField(blank=True, null=True),
        ),
    ]
