# Generated by Django 4.2.2 on 2023-09-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_sitedescription_delete_aboutsite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedescription',
            old_name='about_site_image',
            new_name='site_image',
        ),
    ]
