# Generated by Django 4.2.2 on 2023-09-01 13:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_rename_about_site_image_sitedescription_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedescription',
            name='site_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/static/blog/img/admin_avatar.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
