# Generated by Django 4.2.2 on 2023-09-09 09:51

import ckeditor_uploader.fields
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_sitedescription_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitedescription',
            name='site_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/static/blog/img/admin_avatar.png', upload_to='uploads/', verbose_name='Аватар'),
        ),
    ]
