# Generated by Django 4.2.2 on 2023-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_feedback_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
