# Generated by Django 4.2.2 on 2023-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0013_alter_emailsubscription_email_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feedback_ip",
            field=models.CharField(
                default="0", max_length=256, verbose_name="IP-адрес"
            ),
            preserve_default=False,
        ),
    ]
