# Generated by Django 4.2.2 on 2023-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0014_feedback_feedback_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedescription",
            name="site_image",
            field=models.ImageField(
                blank=True, upload_to="uploads/", verbose_name="Аватар"
            ),
        ),
    ]
