# Generated by Django 4.2.2 on 2023-11-03 19:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0015_alter_sitedescription_site_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("about_me", ckeditor_uploader.fields.RichTextUploadingField()),
                ("contacts", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "site_image",
                    models.ImageField(
                        blank=True, upload_to="uploads/", verbose_name="Аватар"
                    ),
                ),
            ],
            options={
                "verbose_name": "О сайте",
                "verbose_name_plural": "О сайте",
            },
        ),
        migrations.DeleteModel(
            name="SiteDescription",
        ),
    ]
