# Generated by Django 4.2.2 on 2023-11-04 17:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0016_sitesettings_delete_sitedescription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Настройки", "verbose_name_plural": "Настройки"},
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_me",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Об авторе (описание)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contacts",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Об авторе (контакты)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание сайта"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_image",
            field=models.ImageField(
                blank=True,
                upload_to="uploads/",
                verbose_name="Фотография на главной странице",
            ),
        ),
    ]
