# Generated by Django 4.2.2 on 2023-11-05 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0017_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_description",
        ),
    ]
