# Generated by Django 4.2.2 on 2024-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0018_remove_sitesettings_site_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="is_subscribe",
            field=models.BooleanField(
                default=True, verbose_name="Возможность подписки"
            ),
            preserve_default=False,
        ),
    ]
