# Generated by Django 4.2.2 on 2024-06-23 21:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0019_sitesettings_is_subscribe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_me",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_image",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_site",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="О сайте (описание)"
            ),
        ),
    ]
