# Generated by Django 4.2.2 on 2024-06-26 17:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0020_remove_sitesettings_about_me_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_me",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="О сайте (страница)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание сайта"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_site",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="О сайте (сайдбар)"
            ),
        ),
    ]
