# Generated by Django 4.2.2 on 2025-04-12 15:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0022_alter_sitesettings_about_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_site",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="description",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_me",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Описание сайта"
            ),
        ),
    ]
