# Generated by Django 4.2.2 on 2023-07-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='blog_articl_search__4a6f55_gin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='search_vector',
        ),
    ]
