# Generated by Django 4.2.2 on 2023-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_blog_articl_search__4a6f55_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=24, verbose_name='Статус'),
        ),
    ]
