# Generated by Django 4.2.2 on 2023-08-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_feedback_alter_emailsubscription_subscription_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
