# Generated by Django 4.2.2 on 2023-08-24 21:33

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_level_tag_lft_tag_rght_tag_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.tag', verbose_name='Родительский тег'),
        ),
    ]
