# Generated by Django 4.2.2 on 2023-09-14 17:55
from django.contrib.postgres.search import SearchVector
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

class Migration(migrations.Migration):
    
    def compute_search_vector(apps, schema_editor):
        Article = apps.get_model("blog", "Article")
        Article.objects.update(search_vector=SearchVector("title", "body"))

    dependencies = [
        ('blog', '0014_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='blog_articl_search__4a6f55_gin'),
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
