# Generated by Django 4.2.2 on 2023-10-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_alter_article_search_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Подкатегория")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегории",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "category": models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.category",
                        verbose_name="Категория",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
