# Generated by Django 4.2.2 on 2023-10-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_subcategory_article_subcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
