# Generated by Django 4.2.2 on 2023-10-29 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_subcategory_options_alter_article_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
    ]
