# Generated by Django 4.2.2 on 2023-10-29 11:25

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_remove_category_parent_subcategory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="blog.category",
                verbose_name="Родительская категория",
            ),
        ),
    ]
