# Generated by Django 4.2.2 on 2023-10-30 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="next_article",
        ),
        migrations.RemoveField(
            model_name="article",
            name="prev_article",
        ),
    ]
