# Generated by Django 4.2.2 on 2023-10-31 14:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_remove_article_next_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="description",
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
