# Generated by Django 4.2.2 on 2023-11-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_remove_subcategory_description_alter_article_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.RemoveField(
            model_name="category",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="category",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Категория"),
        ),
    ]
