# Generated by Django 4.2.2 on 2023-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_remove_category_level_remove_category_lft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_ip",
            field=models.CharField(
                default="0", max_length=256, verbose_name="IP-адрес"
            ),
            preserve_default=False,
        ),
    ]
