# Generated by Django 4.2.2 on 2023-11-04 17:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_comment_comment_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Текст статьи"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Краткое содержание"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
    ]
