# Generated by Django 4.2.2 on 2024-02-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0026_alter_article_body_alter_article_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Черновик"),
        ),
    ]
