# Generated by Django 4.2.2 on 2024-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0028_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_draft",
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                default="draft",
                max_length=64,
                verbose_name="Статус",
            ),
        ),
    ]
