# Generated by Django 4.2.2 on 2024-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_remove_article_is_draft_article_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(verbose_name="Краткое содержание"),
        ),
    ]
