# Generated by Django 4.2.2 on 2024-02-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_alter_article_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="keywords",
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, verbose_name="Мета-описание"),
        ),
    ]
