# Generated by Django 4.2.2 on 2024-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_remove_article_keywords_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(verbose_name="Время создания"),
        ),
    ]
