# Generated by Django 4.2.2 on 2025-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_alter_article_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("textbook", "Учебник"), ("projects", "Проекты")],
                default="textbook",
                max_length=64,
                verbose_name="Тип",
            ),
        ),
    ]
