# Generated by Django 4.2.2 on 2025-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0033_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sort_field",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Номер статьи для сортировки"
            ),
        ),
    ]
