# Generated by Django 4.2.2 on 2025-04-16 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0035_alter_article_sort_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["sort_field"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
