# Generated by Django 4.2.2 on 2025-04-17 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0036_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["title"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="sort_field",
        ),
    ]
