# Generated by Django 4.2.2 on 2025-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0037_alter_article_options_remove_article_sort_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["main_number", "sub_number"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="main_number",
            field=models.PositiveIntegerField(default=0, verbose_name="Основной номер"),
        ),
        migrations.AddField(
            model_name="article",
            name="sub_number",
            field=models.PositiveIntegerField(default=0, verbose_name="Подномер"),
        ),
    ]
