# Generated by Django 4.2.2 on 2025-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0038_alter_article_options_article_main_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
