# Generated by Django 4.2.2 on 2025-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0039_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="code",
            field=models.TextField(blank=True, null=True, verbose_name="Код"),
        ),
        migrations.AddField(
            model_name="article",
            name="image_type",
            field=models.CharField(
                choices=[("image", "Изображение"), ("code", "Код")],
                default="code",
                max_length=64,
                verbose_name="Тип изображения",
            ),
        ),
    ]
