# Generated by Django 4.2.2 on 2025-10-14 22:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0040_article_code_article_image_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="code",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_type",
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Краткое содержание"
            ),
        ),
    ]
