# Generated by Django 4.2.2 on 2025-10-18 18:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0042_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="is_subscribe",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание сайта"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="about_me",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Об авторе"
            ),
        ),
    ]
